## 데이터 수집 자동화

### 셀레니움
> 웹 브라우저를 자동으로 제어하는 파이썬 라이브러리(패키지)
- 기능
    - 브라우저실행
    - 웹 페이지 로드(접속)
    - 입력창에 글자 입력(아이디,패스워드 등)
    - 버튼 클릭
    - 페이지 이동
    - 화면에 표시된 텍스트 추출
    - 특정 이미지 저장 / 화면 스크린 캡쳐
    - 반복 자동화

- 정적인 HTML 은 Beautifulsoup4, request 패키지로 수집가능
- 동적인 웹화면은 Selenium이 강력함. 정적인 웹페이지도 가능

#### 웹 브라우저 실행

In [1]:
# 셀레니움 패지키 로드
from selenium import webdriver
import pandas as pd

In [2]:
# 웹 브라우저 프로세스를 파이썬이 dirver라는 변수로 관리
driver = webdriver.Chrome()

driver.get("http://www.naver.com")

In [3]:
# 웹 브라우저 종료
driver.quit()

#### 웹 페이지스크랩핑 실습

앞에서 `driver.quit()`으로 종료했으므로 아래 코드 셀을 실행해 새 브라우저를 엽니다. 요소 찾기 실습 전에 이 셀을 먼저 실행하세요. Live Server를 저장소 루트에서 실행해 상품 페이지에 접속할 수 있어야 합니다.

In [4]:
driver = webdriver.Chrome()

driver.get('http://127.0.0.1:5500/chapt04/products.html')

#### 요소 찾기

- 주요 요소 찾기 방식
    - **`By.ID`** : ID로 찾기
    - **`By.CLASS_NAME`** : Class 명으로 찾기
    - `By.TAG_NAME` : 태그명으로 찾기
    - `By.CSS_SELECTOR` : CSS 선택자 방법으로 찾기
    - `By.XPATH` : XPath로 찾기

In [5]:
# CSS 선택자로 요소찾는 함수용 패키지 내 클래스 로드
from selenium.webdriver.common.by import By

In [6]:
# 페이지 내 하나의 데이터만 추출
title = driver.find_element(By.ID,'title')

title.text

'상품목록'

In [7]:
# 페이지 내에서 여러 요소를 동시에 추출
products = driver.find_elements(By.CLASS_NAME, 'product')

len(products)

4

In [8]:
for product in products:
    print(product.text)

키보드 30000
마우스 15000
모니터 250000
바나나 3000

##### CSS 선택자로 요소 추출

In [9]:
products = driver.find_elements(By.CSS_SELECTOR, '.product')

for product in products:
    print(product)
    name = product.find_element(By.CSS_SELECTOR, '.name').text
    price = product.find_element(By.CSS_SELECTOR, '.price').text
    print(name, price)

<selenium.webdriver.remote.webelement.WebElement (session="d847393f21c25534549940d558d06166", element="f.356ADC2B69A4E85C7A19177FAA8F4505.d.AC3B6865A78EFE12AC2C4874D6277A00.e.4")>
키보드 30000
<selenium.webdriver.remote.webelement.WebElement (session="d847393f21c25534549940d558d06166", element="f.356ADC2B69A4E85C7A19177FAA8F4505.d.AC3B6865A78EFE12AC2C4874D6277A00.e.5")>
마우스 15000
<selenium.webdriver.remote.webelement.WebElement (session="d847393f21c25534549940d558d06166", element="f.356ADC2B69A4E85C7A19177FAA8F4505.d.AC3B6865A78EFE12AC2C4874D6277A00.e.6")>
모니터 250000
<selenium.webdriver.remote.webelement.WebElement (session="d847393f21c25534549940d558d06166", element="f.356ADC2B69A4E85C7A19177FAA8F4505.d.AC3B6865A78EFE12AC2C4874D6277A00.e.7")>
바나나 3000

#### 입력창 입력

In [10]:
keyword_input = driver.find_element(By.ID, 'keyword')
keyword_input.send_keys('USB');

In [11]:
keyword_input.clear()

In [12]:
keyword_input.send_keys('테슬라')

In [13]:
# 입력태그에서 텍스트 가져오기
keyword_str = driver.find_element(By.ID, 'keyword')

keyword_str.get_attribute('value')

'테슬라'

##### 버튼 클릭

In [14]:
button = driver.find_element(By.ID, 'search-btn')
button.click()

##### 명시적 대기
> 링크 클릭으로 다른 페이지 이동, 검색 후 결과 대기까지 시간이 소요
- `time.sleep(2)` 2초 동안 대기 등의 파이썬 기본 함수가 제약사항이 많음
- 특정조건이 만족할때까지 대기하는 로직 사용

In [15]:
# 명시적 대기를 위한 패키지 로드
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [17]:
# 여러 작업을 수행 후 
wait = WebDriverWait(driver, 10)

title = wait.until(
    EC.presence_of_element_located((By.ID, 'title'))
)

title.text

'상품목록'

##### 데이터 수집하기

In [21]:
products = driver.find_elements(By.CLASS_NAME, 'product')

result = []

for product in products:
 name = product.find_element(By.CSS_SELECTOR, '.name').text
 price = product.find_element(By.CLASS_NAME, 'price').text

 result.append({'name':name, 'price':price})

In [22]:
result

[{'name': '키보드', 'price': '30000'},
 {'name': '마우스', 'price': '15000'},
 {'name': '모니터', 'price': '250000'},
 {'name': '바나나', 'price': '3000'}]

In [23]:
df = pd.DataFrame(result)
df

  name   price
0  키보드   30000
1  마우스   15000
2  모니터  250000
3  바나나    3000

In [24]:
df.to_csv('../data/scrap_products.csv', encoding='utf-8')

#### 정리
- 웹 스크래핑시 필요요소
    - 웹드라이버로 웹사이트 오픈
    - 필요 요소 찾기
    - 입력태그 찾기
    - 버튼 요소 찾기
    - 입력하고 버튼 클릭해서 동작
    - 데이터 가져오기
    - 화면이 갱신 되기까지 명시적으로 대기

#### 실습

##### 멜로 사이트 TOP 100 스크랩핑

In [70]:
# 패키지 로드
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [72]:
driver = webdriver.Chrome()
wait = WebDriverWait(driver, 10)

driver.get('https://www.melon.com/chart/index.htm')

company_name = wait.until(
    EC.presence_of_element_located((By.ID,'footer'))
)

#### 차트의 곡 행 가져오기

In [73]:
# CSS 선택자 입력 태그 + .css 동일한 기능
# songs50 = driver.find_elements(By.CSS_SELECTOR, 'tr.lst50, .lst100')
songs50 = driver.find_elements(By.CSS_SELECTOR, '.lst50, .lst100')

#len(songs50)
for song in songs50:
    #노래 순위
    rank = song.find_element(By.CSS_SELECTOR, '.rank').text

    #노래 제목
    title = song.find_element(By.CSS_SELECTOR, '.rank01 > span > a').text
    #가수 명
    singer = song.find_element(By.CSS_SELECTOR, '.rank02 a').text
    #앨범 명
    album = song.find_element(By.CSS_SELECTOR, '.rank03 a').text
    #좋아요 갯수
    like = song.find_element(By.CLASS_NAME, 'cnt').text
   

    print(rank, title, singer, album, like)

1 퇴사할게여 (Narr. 기안84) 소연 (SOYEON) 끝내주는 인생 39,516
2 LOVE ATTACK RESCENE (리센느) SCENEDROME 153,145
3 갑자기 아이오아이 (I.O.I) I.O.I 3rd MINI ALBUM [I.O.I : LOOP] 80,177
4 Deja Vu RESCENE (리센느) Dearest 58,937
5 Pretty Girl RESCENE (리센느) Pretty Girl - Special Single 66,158
6 REDRED CORTIS (코르티스) GREENGREEN 91,127
7 만찬가 태연 (TAEYEON) J-POP REMAKE Vol.1 49,656
8 BAD ATEEZ(에이티즈) GOLDEN HOUR : Part.5 33,782
9 BiiiG BIGBANG (빅뱅) BiiiG 56,957
10 LEMONADE aespa LEMONADE - The 2nd Album 59,589
11 Drowning WOODZ OO-LI 309,371
12 It′s Me 아일릿(ILLIT) MAMIHLAPINATAPAI 59,753
13 이 별로부터 아이유 이 별로부터 31,645
14 Dear my crazy soulmate 아이유 이 별로부터 28,191
15 Good Goodbye 화사 (HWASA) Good Goodbye 125,781
16 사랑하게 될 거야 한로로 이상비행 149,812
17 노스탈지아 BIG Naughty (서동현) 노스탈지아 32,575
18 RUDE! Hearts2Hearts (하츠투하츠) RUDE! 75,754
19 캐치 캐치 YENA (최예나) LOVE CATCHER 52,063
20 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지 AKMU (악뮤) 항해 496,825
21 사랑은 늘 도망가 임영웅 신사와 아가씨 OST Part.2 241,229
22 Popcorn 도경수(D.O.) 성장 - THE 3RD MINI ALBUM 94,931
23 0+0 한로로 자몽살구클럽 125,732
24 생각을 멈추다 보면 최유리 생각을 멈추다 보면 50,901
25 Skibidi 소녀시대-효리수 (Girls' Generation-HRS) Skibidi 17,105
26 타임캡슐 다비치 타임캡슐 79,517
27 여름아 부탁해 볼빨간사춘기 여름아 부탁해 29,209
28 기쁨, 슬픔, 아름다운 마음 AKMU (악뮤) 개화 93,567
29 너의 모든 순간 성시경 별에서 온 그대 OST Part.7 326,961
30 꿈꾸던 어른이 되었나요? 머무르 꿈꾸던 어른이 되었나요? 20,017
31 Pop Off Pop Off KiiiKiii (키키) WhyKiiiKiii 23,135
32 HOME SWEET HOME (feat. 태양, 대성) G-DRAGON HOME SWEET HOME (feat. 태양, 대성) 234,016
33 Lemon Tang Hearts2Hearts (하츠투하츠) Lemon Tang - The 2nd Mini Album 34,196
34 소문의 낙원 AKMU (악뮤) 개화 90,833
35 어제보다 슬픈 오늘 우디 (Woody) 어제보다 슬픈 오늘 91,176
36 내게 사랑이 뭐냐고 물어본다면 로이킴 내게 사랑이 뭐냐고 물어본다면 102,975
37 404 (New Era) KiiiKiii (키키) Delulu Pack 73,285
38 Blue Valentine NMIXX Blue Valentine 121,638
39 천상연 이창섭 천상연 (웹툰 '선녀외전' X 이창섭 (LEE CHANGSUB)) 150,899
40 또또 임영웅 IM HERO 10 30,591
41 그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection)) 너드커넥션 (Nerd Connection) 그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection)) 179,560
42 BANG BANG IVE (아이브) REVIVE+ 69,092
43 Runaway RESCENE (리센느) Runaway 35,675
44 toxic till the end 로제 (ROSÉ) rosie 162,242
45 우리들의 블루스 임영웅 IM HERO 128,617
46 모든 날, 모든 순간 (Every day, Every Moment) 폴킴 '키스 먼저 할까요?' OST Part.3 433,471
47 멸종위기사랑 이찬혁 EROS 106,837
48 오늘만 I LOVE YOU BOYNEXTDOOR 오늘만 I LOVE YOU 190,830
49 봄 내음보다 너를 김나영 봄 내음보다 너를 142,891
50 한 페이지가 될 수 있게 DAY6 (데이식스) The Book of Us : Gravity 371,541
51 너에게 닿기를 10CM 너에게 닿기를 156,503
52 순간을 영원처럼 임영웅 IM HERO 2 53,766
53 모르시나요(PROD.로코베리) 조째즈 모르시나요 111,091
54 소나기 이클립스 (ECLIPSE) 선재 업고 튀어 OST Part 1 201,703
55 주저하는 연인들을 위해 잔나비 전설 454,337
56 뛰어(JUMP) BLACKPINK 뛰어(JUMP) 100,212
57 Guitarist 도경수(D.O.) DOPAMINE - The 4th Mini Album 16,087
58 Whiplash aespa Whiplash - The 5th Mini Album 156,411
59 부디 행복해질 것 임영웅 IM HERO 10 27,075
60 청춘만화 이무진 만화 (滿花) 107,814
61 HAPPY DAY6 (데이식스) Fourever 218,914
62 Heavy Serenade NMIXX Heavy Serenade 56,250
63 Seven (feat. Latto) - Clean Ver. 정국 Seven (feat. Latto) - Clean Ver. 233,900
64 SWIM 방탄소년단 ARIRANG 64,572
65 예뻤어 DAY6 (데이식스) Every DAY6 February 381,753
66 Golden HUNTR/X KPop Demon Hunters (Soundtrack from the Netflix Film) 193,575
67 이 밤을 빌려 말해요 PLAVE 이 밤을 빌려 말해요 (오늘 밤, 세계에서 이 사랑이 사라진다 해도 X PLAVE) 34,825
68 그대 작은 나의 세상이 되어 카더가든 부재 88,934
69 Baila 임영웅 IM HERO 10 25,839
70 like JENNIE 제니 (JENNIE) Ruby 113,641
71 헤어지자 말해요 박재정 1집 Alone 196,438
72 모이세 임영웅 IM HERO 10 26,643
73 Love wins all 아이유 The Winning 226,757
74 Dynamite 방탄소년단 Dynamite (DayTime Version) 460,581
75 입춘 한로로 입춘 85,134
76 Die With A Smile Lady Gaga Die With A Smile 142,470
77 살아온 우리에게 임영웅 IM HERO 10 24,792
78 나는 반딧불 황가람 나는 반딧불 160,831
79 Welcome to the Show DAY6 (데이식스) Fourever 203,300
80 사랑인가 봐 멜로망스 사랑인가 봐 (사내맞선 OST 스페셜 트랙) 240,131
81 봄날 방탄소년단 YOU NEVER WALK ALONE 501,266
82 첫 만남은 계획대로 되지 않아 TWS (투어스) Sparkling Blue 177,374
83 미워요 RE 임영웅 IM HERO 10 24,348
84 APT. 로제 (ROSÉ) APT. 222,607
85 Vitamin ME 프로미스나인 Glow ME 20,258
86 청혼하지 않을 이유를 못 찾았어 이무진 청혼하지 않을 이유를 못 찾았어 77,966
87 다정히 내 이름을 부르면 경서예지 다정히 내 이름을 부르면 (경서예지 x 전건호) 225,994
88 Hype Boy NewJeans NewJeans 1st EP 'New Jeans' 318,221
89 모래 알갱이 RE 임영웅 IM HERO 10 23,981
90 STYLE Hearts2Hearts (하츠투하츠) STYLE 66,842
91 Magnetic 아일릿(ILLIT) SUPER REAL ME 149,307
92 CRASH ALLDAY PROJECT CRASH 5,223
93 Love Love Love (Feat. Yoong Jin Of Casker) 에픽하이 (EPIK HIGH) Remapping The Human Soul 129,855
94 사랑은 늘 도망가 RE 임영웅 IM HERO 10 23,785
95 A Bientot RE 임영웅 IM HERO 10 23,764
96 Less than a Lover 제니 (JENNIE) Less than a Lover 27,099
97 New York 임영웅 IM HERO 10 24,268
98 그댈 위한 멜로디 임영웅 IM HERO 2 42,734
99 사랑은 봄비처럼...이별은 겨울비처럼... 임현정 All That Love 76,461
100 REBEL HEART IVE (아이브) IVE EMPATHY 122,858

In [ ]:
songs50 = driver.find_elements(By.CSS_SELECTOR, '.lst50, .lst100')
datas = []

#len(songs50)
for song in songs50:
    #노래 순위
    rank = song.find_element(By.CSS_SELECTOR, '.rank').text
    #노래 제목
    title = song.find_element(By.CSS_SELECTOR, '.rank01 > span > a').text
    #가수 명
    singer = song.find_element(By.CSS_SELECTOR, '.rank02 a').text
    #앨범 명
    album = song.find_element(By.CSS_SELECTOR, '.rank03 a').text
    #좋아요 갯수
    like = song.find_element(By.CLASS_NAME, 'cnt').text

    datas.append({
        '순위':rank,
        '제목':title,
        '가수':singer,
        '앨범':album,
        '좋아요':like
    })

In [75]:
driver.quit()

In [76]:
df.melon100 = pd.DataFrame(datas)
df.melon100

,순위,단계,제목,가수,앨범,좋아요
0,1,순위 동일,퇴사할게여 (Narr. 기안84),소연 (SOYEON),끝내주는 인생,"39,516"
1,2,순위 동일,LOVE ATTACK,RESCENE (리센느),SCENEDROME,"153,145"
2,3,순위 동일,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],"80,177"
3,4,순위 동일,Deja Vu,RESCENE (리센느),Dearest,"58,937"
4,5,순위 동일,Pretty Girl,RESCENE (리센느),Pretty Girl - Special Single,"66,158"
...,...,...,...,...,...,...
95,96,3단계 하락,Less than a Lover,제니 (JENNIE),Less than a Lover,"27,099"
96,97,15단계 하락,New York,임영웅,IM HERO 10,"24,268"
97,98,순위 동일,그댈 위한 멜로디,임영웅,IM HERO 2,"42,734"
98,99,1단계 상승,사랑은 봄비처럼...이별은 겨울비처럼...,임현정,All That Love,"76,461"
99,100,1단계 하락,REBEL HEART,IVE (아이브),IVE EMPATHY,"122,858"

In [52]:
df.melon100.to_csv('../data/melon100_261001.csv', encoding='utf-8')

In [80]:
songs50 = driver.find_elements(By.CSS_SELECTOR, '.lst50, .lst100')

datas = []

#len(songs50)
for song in songs50:
    #노래 순위
    rank = song.find_element(By.CSS_SELECTOR, '.rank').text
    #노래 제목
    title = song.find_element(By.CSS_SELECTOR, '.rank01 > span > a').text
    #가수 명
    singer = song.find_element(By.CSS_SELECTOR, '.rank02 a').text
    #앨범 명
    album = song.find_element(By.CSS_SELECTOR, '.rank03 a').text
    
    #좋아요 갯수
    like = song.find_element(By.CLASS_NAME, 'cnt').text
    #단계상승하락
    rank_ud = song.find_element(By.CSS_SELECTOR, '.rank_wrap').get_attribute('title')

    datas.append({
            '순위':rank,
            '단계':rank_ud,
            '제목':title,
            '가수':singer,
            '앨범':album,
            '좋아요':like
        })

In [79]:
driver = webdriver.Chrome()
driver.get('https://www.melon.com/chart/index.htm')

wait = WebDriverWait(driver, 10)
wait.until(
    EC.presence_of_element_located((By.CSS_SELECTOR, '.lst50'))
)